name: Crystal Beasley
description: Pixels on thread
url: http://crystalbeasley.com
baseurl: /

markdown: rdiscount

permalink: /:year/:month/:day/:title
lsi: false

exclude:
- CNAME
- README.md
- /scss/